# Generated by Django 2.1.7 on 2019-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
