# Generated by Django 2.1.7 on 2019-02-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='active',
        ),
    ]
